package rules

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// Load reads a YAML file and validates it
func Load(path string) (RuleSet, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return RuleSet{}, fmt.Errorf("failed to read file %s: %w", path, err)
	}

	var rs RuleSet
	if err := yaml.Unmarshal(data, &rs); err != nil {
		return RuleSet{}, fmt.Errorf("failed to parse YAML from %s: %w", path, err)
	}

	if err := Validate(rs); err != nil {
		return RuleSet{}, fmt.Errorf("validation failed for %s: %w", path, err)
	}

	return rs, nil
}

// Save writes a RuleSet to a YAML file with version header comment
func Save(path string, rs RuleSet) error {
	// Add version header comment
	data := []byte("# rules.yaml - generated by project-check\n# version: 1\n\n")
	
	yamlData, err := yaml.Marshal(&rs)
	if err != nil {
		return fmt.Errorf("failed to marshal YAML: %w", err)
	}
	
	data = append(data, yamlData...)
	
	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", path, err)
	}
	
	return nil
}
